databases:
  - name: sample-space-be
    databaseName: sample_space_be_api_production
    user: sample_space_be_api_production_user

services:
  - type: web
    name: sample-space-be
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample-space-be-api_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false