databases:
  - name: sampleSpaceBe
    databaseName: sampleSpaceBeApiProduction
    user: sampleSpaceBeApi

services:
  - type: web
    name: sampleSpaceBe
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sampleSpaceBeApiProduction
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false