databases:
  - name: sample-space-be
    databaseName: sample-space-be-api-production
    user: sample-space-be-api

services:
  - type: web
    name: sample-space-be
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample-space-be
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false